// Copyright (c) 2019, Apple Inc. All rights reserved.
//
// Use of this source code is governed by a BSD-3-clause license that can be
// found in LICENSE.txt or at https://opensource.org/licenses/BSD-3-Clause

//
// - A Program is the container with following information
//     - set of functions: Function defines a program block to be executed
//     - A model can have multiple functions defined and will have a single point of entry.
// - A Function consists of
//     - List of named inputs and output types
//     - A block defining scope for a function - similar to a function in C/C++
// - A Block consists of
//     - List of named inputs and output names
//     - Topologically sorted Ops
// - A Op consists of
//     - List of named inputs and outputs (name, type) pair
//     - Optionally, blocks for Control-Flow
//
// Programs, functions, blocks, ops, and tensor types all can contain an optional set of attributes.
//
// == Identifiers ==
// Identifiers, generally used for names and keys, must match the
// regular expression [A-Za-z\_][A-Za-z0-9\_@]*

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: MIL.proto

package milspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported data types
type DataType int32

const (
	// 0-10 reserved for special types
	DataType_UNUSED_TYPE DataType = 0 // not currently in use
	DataType_BOOL        DataType = 1
	DataType_STRING      DataType = 2 // arbitrary sequence of bytes
	// Floats
	DataType_FLOAT8E4M3FN DataType = 40
	DataType_FLOAT8E5M2   DataType = 41
	DataType_FLOAT16      DataType = 10
	DataType_FLOAT32      DataType = 11
	DataType_FLOAT64      DataType = 12
	DataType_BFLOAT16     DataType = 13
	// Ints
	DataType_INT8  DataType = 21
	DataType_INT16 DataType = 22
	DataType_INT32 DataType = 23
	DataType_INT64 DataType = 24
	DataType_INT4  DataType = 25
	// UInts
	DataType_UINT8  DataType = 31
	DataType_UINT16 DataType = 32
	DataType_UINT32 DataType = 33
	DataType_UINT64 DataType = 34
	DataType_UINT4  DataType = 35
	DataType_UINT2  DataType = 36
	DataType_UINT1  DataType = 37
	DataType_UINT6  DataType = 38
	DataType_UINT3  DataType = 39
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "UNUSED_TYPE",
		1:  "BOOL",
		2:  "STRING",
		40: "FLOAT8E4M3FN",
		41: "FLOAT8E5M2",
		10: "FLOAT16",
		11: "FLOAT32",
		12: "FLOAT64",
		13: "BFLOAT16",
		21: "INT8",
		22: "INT16",
		23: "INT32",
		24: "INT64",
		25: "INT4",
		31: "UINT8",
		32: "UINT16",
		33: "UINT32",
		34: "UINT64",
		35: "UINT4",
		36: "UINT2",
		37: "UINT1",
		38: "UINT6",
		39: "UINT3",
	}
	DataType_value = map[string]int32{
		"UNUSED_TYPE":  0,
		"BOOL":         1,
		"STRING":       2,
		"FLOAT8E4M3FN": 40,
		"FLOAT8E5M2":   41,
		"FLOAT16":      10,
		"FLOAT32":      11,
		"FLOAT64":      12,
		"BFLOAT16":     13,
		"INT8":         21,
		"INT16":        22,
		"INT32":        23,
		"INT64":        24,
		"INT4":         25,
		"UINT8":        31,
		"UINT16":       32,
		"UINT32":       33,
		"UINT64":       34,
		"UINT4":        35,
		"UINT2":        36,
		"UINT1":        37,
		"UINT6":        38,
		"UINT3":        39,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_MIL_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_MIL_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{0}
}

// The top level container.
type Program struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Must be unique within the containing program
	// Names must be valid identifiers as described above.
	Functions map[string]*Function `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DocString string               `protobuf:"bytes,3,opt,name=docString,proto3" json:"docString,omitempty"`
	// Any other attributes not described by other fields.
	// Keys must be valid identifiers as described above.
	Attributes    map[string]*Value `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_MIL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Program) GetFunctions() map[string]*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Program) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *Program) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// A program-level function.
type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Function inputs are unordered (name, ValueType) pairs.
	// Inputs intended to process images must be rank-4 Float32 tensors. Dimensions
	// are interpreted as NCHW, with N == 1 and C being 1 for grayscale and 3 for RGB.
	// Names must be valid identifiers as described above.
	Inputs []*NamedValueType `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// The active block is drawn from this named specialization.
	// This key must exist in `block_specializations`.
	Opset string `protobuf:"bytes,2,opt,name=opset,proto3" json:"opset,omitempty"`
	// Named specializations of this function.
	//
	// Specialization keys are the name of the opset that the
	// function specialization is written in. They must be valid
	// identifiers as described above.
	//
	// Outputs from all blocks must match. They define the outputs
	// of the function.
	// Each block inherits the lexical scope from the function.
	BlockSpecializations map[string]*Block `protobuf:"bytes,3,rep,name=block_specializations,json=blockSpecializations,proto3" json:"block_specializations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Any other attributes not described by other fields.
	// Keys must be valid identifiers as described above.
	Attributes    map[string]*Value `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_MIL_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{1}
}

func (x *Function) GetInputs() []*NamedValueType {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Function) GetOpset() string {
	if x != nil {
		return x.Opset
	}
	return ""
}

func (x *Function) GetBlockSpecializations() map[string]*Block {
	if x != nil {
		return x.BlockSpecializations
	}
	return nil
}

func (x *Function) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// A basic block with a single entry and exit in SSA form.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Infrequently used, these are for operators that may need to give
	// block-local names to input values (e.g. while_loop).
	Inputs []*NamedValueType `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// The names to give to values returned by this block. They must be
	// identifiers as described above.
	//
	// ValueType of outputs[i] is Operation[j].outputs[k].type where
	// i, j and k are indices of block output, block Operation and
	// jth operation's output respectively.
	// this is due to
	// 1. An operation can have more than one output
	// 2. Any one of operation's output could be potentially block's output
	Outputs    []string     `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Operations []*Operation `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	// Any other attributes not described by other fields.
	// Keys must be valid identifiers as described above.
	Attributes    map[string]*Value `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_MIL_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetInputs() []*NamedValueType {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Block) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Block) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Block) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Argument is list of Binding to either name or value
type Argument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arguments     []*Argument_Binding    `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_MIL_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{3}
}

func (x *Argument) GetArguments() []*Argument_Binding {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// A single operation/node/layer.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Examples: "convolution", "cropResize". Operation type defines the
	// expected inputs and output.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Operator arguments
	//
	// Key: parameter name
	// Value: Argument (list of bindings)
	//
	// Value is list of argument binding to given parameter
	// Binding can be a string name (previous operation output or input given to model/block/function)
	//
	//	or a Value (known compile time value for given operation)
	//
	// Argument can be of length 1 (general) or variable length (e.g. concat layer)
	// e.g. {'stride' : ['input_01']}
	// e.g. {'x' : ['input_01', 'input_02', 'input_03', false]}
	Inputs map[string]*Argument `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Names to which to bind values returned by this operation.
	// Names must be:
	//
	//	(*) valid identifiers as described above; and
	//	(*) unique within the current scope.
	Outputs []*NamedValueType `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Nested blocks for loops and conditionals. For example,
	// a conditional block will have two entries here.
	Blocks []*Block `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	// Any other information not captured by other fields.
	// Keys must be valid identifiers as described above.
	Attributes    map[string]*Value `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_MIL_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{4}
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetInputs() map[string]*Argument {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Operation) GetOutputs() []*NamedValueType {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Operation) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Operation) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Named Value parameters
// (name, type) pair
type NamedValueType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this parameter; must be a valid identifier as described above.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This parameter's required type.
	Type          *ValueType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValueType) Reset() {
	*x = NamedValueType{}
	mi := &file_MIL_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValueType) ProtoMessage() {}

func (x *NamedValueType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValueType.ProtoReflect.Descriptor instead.
func (*NamedValueType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{5}
}

func (x *NamedValueType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedValueType) GetType() *ValueType {
	if x != nil {
		return x.Type
	}
	return nil
}

// A type of any kind
type ValueType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ValueType_TensorType
	//	*ValueType_ListType
	//	*ValueType_TupleType
	//	*ValueType_DictionaryType
	//	*ValueType_StateType
	Type          isValueType_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	mi := &file_MIL_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType.ProtoReflect.Descriptor instead.
func (*ValueType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{6}
}

func (x *ValueType) GetType() isValueType_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ValueType) GetTensorType() *TensorType {
	if x != nil {
		if x, ok := x.Type.(*ValueType_TensorType); ok {
			return x.TensorType
		}
	}
	return nil
}

func (x *ValueType) GetListType() *ListType {
	if x != nil {
		if x, ok := x.Type.(*ValueType_ListType); ok {
			return x.ListType
		}
	}
	return nil
}

func (x *ValueType) GetTupleType() *TupleType {
	if x != nil {
		if x, ok := x.Type.(*ValueType_TupleType); ok {
			return x.TupleType
		}
	}
	return nil
}

func (x *ValueType) GetDictionaryType() *DictionaryType {
	if x != nil {
		if x, ok := x.Type.(*ValueType_DictionaryType); ok {
			return x.DictionaryType
		}
	}
	return nil
}

func (x *ValueType) GetStateType() *StateType {
	if x != nil {
		if x, ok := x.Type.(*ValueType_StateType); ok {
			return x.StateType
		}
	}
	return nil
}

type isValueType_Type interface {
	isValueType_Type()
}

type ValueType_TensorType struct {
	TensorType *TensorType `protobuf:"bytes,1,opt,name=tensorType,proto3,oneof"`
}

type ValueType_ListType struct {
	ListType *ListType `protobuf:"bytes,2,opt,name=listType,proto3,oneof"`
}

type ValueType_TupleType struct {
	TupleType *TupleType `protobuf:"bytes,3,opt,name=tupleType,proto3,oneof"`
}

type ValueType_DictionaryType struct {
	DictionaryType *DictionaryType `protobuf:"bytes,4,opt,name=dictionaryType,proto3,oneof"`
}

type ValueType_StateType struct {
	StateType *StateType `protobuf:"bytes,5,opt,name=stateType,proto3,oneof"`
}

func (*ValueType_TensorType) isValueType_Type() {}

func (*ValueType_ListType) isValueType_Type() {}

func (*ValueType_TupleType) isValueType_Type() {}

func (*ValueType_DictionaryType) isValueType_Type() {}

func (*ValueType_StateType) isValueType_Type() {}

type TensorType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The data type stored in a tensor of this type
	DataType DataType `protobuf:"varint,1,opt,name=dataType,proto3,enum=CoreML.Specification.MILSpec.DataType" json:"dataType,omitempty"`
	// The number of dimensions in the tensor shape. rank == -1 implies
	// variable (not fixed) rank
	Rank int64 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	// Tensor shape values; must be of length "rank"
	Dimensions []*Dimension `protobuf:"bytes,3,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Any other tensor type attributes not described by other fields.
	// Keys must be valid identifiers in MIL text syntax.
	Attributes    map[string]*Value `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorType) Reset() {
	*x = TensorType{}
	mi := &file_MIL_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorType) ProtoMessage() {}

func (x *TensorType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorType.ProtoReflect.Descriptor instead.
func (*TensorType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{7}
}

func (x *TensorType) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_UNUSED_TYPE
}

func (x *TensorType) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *TensorType) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TensorType) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type TupleType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recursively define TupleType from ValueType.
	Types         []*ValueType `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleType) Reset() {
	*x = TupleType{}
	mi := &file_MIL_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleType) ProtoMessage() {}

func (x *TupleType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleType.ProtoReflect.Descriptor instead.
func (*TupleType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{8}
}

func (x *TupleType) GetTypes() []*ValueType {
	if x != nil {
		return x.Types
	}
	return nil
}

type ListType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of element stored in a list of this type
	Type *ValueType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The number of elements in a list of this type. May be unknown (variable length)
	Length        *Dimension `protobuf:"bytes,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListType) Reset() {
	*x = ListType{}
	mi := &file_MIL_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListType) ProtoMessage() {}

func (x *ListType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListType.ProtoReflect.Descriptor instead.
func (*ListType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{9}
}

func (x *ListType) GetType() *ValueType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ListType) GetLength() *Dimension {
	if x != nil {
		return x.Length
	}
	return nil
}

// An unordered key-value mapping
type DictionaryType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       *ValueType             `protobuf:"bytes,1,opt,name=keyType,proto3" json:"keyType,omitempty"`
	ValueType     *ValueType             `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryType) Reset() {
	*x = DictionaryType{}
	mi := &file_MIL_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryType) ProtoMessage() {}

func (x *DictionaryType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryType.ProtoReflect.Descriptor instead.
func (*DictionaryType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{10}
}

func (x *DictionaryType) GetKeyType() *ValueType {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *DictionaryType) GetValueType() *ValueType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

type StateType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrappedType   *ValueType             `protobuf:"bytes,1,opt,name=wrappedType,proto3" json:"wrappedType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateType) Reset() {
	*x = StateType{}
	mi := &file_MIL_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateType) ProtoMessage() {}

func (x *StateType) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateType.ProtoReflect.Descriptor instead.
func (*StateType) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{11}
}

func (x *StateType) GetWrappedType() *ValueType {
	if x != nil {
		return x.WrappedType
	}
	return nil
}

type Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Dimension:
	//
	//	*Dimension_Constant
	//	*Dimension_Unknown
	Dimension     isDimension_Dimension `protobuf_oneof:"dimension"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_MIL_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{12}
}

func (x *Dimension) GetDimension() isDimension_Dimension {
	if x != nil {
		return x.Dimension
	}
	return nil
}

func (x *Dimension) GetConstant() *Dimension_ConstantDimension {
	if x != nil {
		if x, ok := x.Dimension.(*Dimension_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

func (x *Dimension) GetUnknown() *Dimension_UnknownDimension {
	if x != nil {
		if x, ok := x.Dimension.(*Dimension_Unknown); ok {
			return x.Unknown
		}
	}
	return nil
}

type isDimension_Dimension interface {
	isDimension_Dimension()
}

type Dimension_Constant struct {
	Constant *Dimension_ConstantDimension `protobuf:"bytes,1,opt,name=constant,proto3,oneof"`
}

type Dimension_Unknown struct {
	Unknown *Dimension_UnknownDimension `protobuf:"bytes,2,opt,name=unknown,proto3,oneof"`
}

func (*Dimension_Constant) isDimension_Dimension() {}

func (*Dimension_Unknown) isDimension_Dimension() {}

// See Variable vs Value primer above.
type Value struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DocString string                 `protobuf:"bytes,1,opt,name=docString,proto3" json:"docString,omitempty"` // optional human-readable texts.
	Type      *ValueType             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_ImmediateValue_
	//	*Value_BlobFileValue_
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_MIL_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{13}
}

func (x *Value) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *Value) GetType() *ValueType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetImmediateValue() *Value_ImmediateValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ImmediateValue_); ok {
			return x.ImmediateValue
		}
	}
	return nil
}

func (x *Value) GetBlobFileValue() *Value_BlobFileValue {
	if x != nil {
		if x, ok := x.Value.(*Value_BlobFileValue_); ok {
			return x.BlobFileValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_ImmediateValue_ struct {
	ImmediateValue *Value_ImmediateValue `protobuf:"bytes,3,opt,name=immediateValue,proto3,oneof"`
}

type Value_BlobFileValue_ struct {
	BlobFileValue *Value_BlobFileValue `protobuf:"bytes,5,opt,name=blobFileValue,proto3,oneof"`
}

func (*Value_ImmediateValue_) isValue_Value() {}

func (*Value_BlobFileValue_) isValue_Value() {}

type TensorValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TensorValue_Floats
	//	*TensorValue_Ints
	//	*TensorValue_Bools
	//	*TensorValue_Strings
	//	*TensorValue_LongInts
	//	*TensorValue_Doubles
	//	*TensorValue_Bytes
	Value         isTensorValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue) Reset() {
	*x = TensorValue{}
	mi := &file_MIL_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue) ProtoMessage() {}

func (x *TensorValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue.ProtoReflect.Descriptor instead.
func (*TensorValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14}
}

func (x *TensorValue) GetValue() isTensorValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TensorValue) GetFloats() *TensorValue_RepeatedFloats {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Floats); ok {
			return x.Floats
		}
	}
	return nil
}

func (x *TensorValue) GetInts() *TensorValue_RepeatedInts {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Ints); ok {
			return x.Ints
		}
	}
	return nil
}

func (x *TensorValue) GetBools() *TensorValue_RepeatedBools {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Bools); ok {
			return x.Bools
		}
	}
	return nil
}

func (x *TensorValue) GetStrings() *TensorValue_RepeatedStrings {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Strings); ok {
			return x.Strings
		}
	}
	return nil
}

func (x *TensorValue) GetLongInts() *TensorValue_RepeatedLongInts {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_LongInts); ok {
			return x.LongInts
		}
	}
	return nil
}

func (x *TensorValue) GetDoubles() *TensorValue_RepeatedDoubles {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Doubles); ok {
			return x.Doubles
		}
	}
	return nil
}

func (x *TensorValue) GetBytes() *TensorValue_RepeatedBytes {
	if x != nil {
		if x, ok := x.Value.(*TensorValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

type isTensorValue_Value interface {
	isTensorValue_Value()
}

type TensorValue_Floats struct {
	Floats *TensorValue_RepeatedFloats `protobuf:"bytes,1,opt,name=floats,proto3,oneof"`
}

type TensorValue_Ints struct {
	Ints *TensorValue_RepeatedInts `protobuf:"bytes,2,opt,name=ints,proto3,oneof"`
}

type TensorValue_Bools struct {
	Bools *TensorValue_RepeatedBools `protobuf:"bytes,3,opt,name=bools,proto3,oneof"`
}

type TensorValue_Strings struct {
	Strings *TensorValue_RepeatedStrings `protobuf:"bytes,4,opt,name=strings,proto3,oneof"`
}

type TensorValue_LongInts struct {
	LongInts *TensorValue_RepeatedLongInts `protobuf:"bytes,5,opt,name=longInts,proto3,oneof"`
}

type TensorValue_Doubles struct {
	Doubles *TensorValue_RepeatedDoubles `protobuf:"bytes,6,opt,name=doubles,proto3,oneof"`
}

type TensorValue_Bytes struct {
	Bytes *TensorValue_RepeatedBytes `protobuf:"bytes,7,opt,name=bytes,proto3,oneof"`
}

func (*TensorValue_Floats) isTensorValue_Value() {}

func (*TensorValue_Ints) isTensorValue_Value() {}

func (*TensorValue_Bools) isTensorValue_Value() {}

func (*TensorValue_Strings) isTensorValue_Value() {}

func (*TensorValue_LongInts) isTensorValue_Value() {}

func (*TensorValue_Doubles) isTensorValue_Value() {}

func (*TensorValue_Bytes) isTensorValue_Value() {}

type TupleValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comment: TupleValue is recursively defined from Value.
	Values        []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleValue) Reset() {
	*x = TupleValue{}
	mi := &file_MIL_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleValue) ProtoMessage() {}

func (x *TupleValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleValue.ProtoReflect.Descriptor instead.
func (*TupleValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{15}
}

func (x *TupleValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_MIL_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{16}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type DictionaryValue struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Values        []*DictionaryValue_KeyValuePair `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryValue) Reset() {
	*x = DictionaryValue{}
	mi := &file_MIL_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryValue) ProtoMessage() {}

func (x *DictionaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryValue.ProtoReflect.Descriptor instead.
func (*DictionaryValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{17}
}

func (x *DictionaryValue) GetValues() []*DictionaryValue_KeyValuePair {
	if x != nil {
		return x.Values
	}
	return nil
}

type Argument_Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Binding:
	//
	//	*Argument_Binding_Name
	//	*Argument_Binding_Value
	Binding       isArgument_Binding_Binding `protobuf_oneof:"binding"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument_Binding) Reset() {
	*x = Argument_Binding{}
	mi := &file_MIL_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument_Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument_Binding) ProtoMessage() {}

func (x *Argument_Binding) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument_Binding.ProtoReflect.Descriptor instead.
func (*Argument_Binding) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Argument_Binding) GetBinding() isArgument_Binding_Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *Argument_Binding) GetName() string {
	if x != nil {
		if x, ok := x.Binding.(*Argument_Binding_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *Argument_Binding) GetValue() *Value {
	if x != nil {
		if x, ok := x.Binding.(*Argument_Binding_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isArgument_Binding_Binding interface {
	isArgument_Binding_Binding()
}

type Argument_Binding_Name struct {
	// The name of a previously defined value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type Argument_Binding_Value struct {
	// A compile time constant.
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*Argument_Binding_Name) isArgument_Binding_Binding() {}

func (*Argument_Binding_Value) isArgument_Binding_Binding() {}

type Dimension_ConstantDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension_ConstantDimension) Reset() {
	*x = Dimension_ConstantDimension{}
	mi := &file_MIL_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension_ConstantDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension_ConstantDimension) ProtoMessage() {}

func (x *Dimension_ConstantDimension) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension_ConstantDimension.ProtoReflect.Descriptor instead.
func (*Dimension_ConstantDimension) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{12, 0}
}

func (x *Dimension_ConstantDimension) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Dimension_UnknownDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variadic      bool                   `protobuf:"varint,1,opt,name=variadic,proto3" json:"variadic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension_UnknownDimension) Reset() {
	*x = Dimension_UnknownDimension{}
	mi := &file_MIL_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension_UnknownDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension_UnknownDimension) ProtoMessage() {}

func (x *Dimension_UnknownDimension) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension_UnknownDimension.ProtoReflect.Descriptor instead.
func (*Dimension_UnknownDimension) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{12, 1}
}

func (x *Dimension_UnknownDimension) GetVariadic() bool {
	if x != nil {
		return x.Variadic
	}
	return false
}

// An immediate value stored within the proto
type Value_ImmediateValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_ImmediateValue_Tensor
	//	*Value_ImmediateValue_Tuple
	//	*Value_ImmediateValue_List
	//	*Value_ImmediateValue_Dictionary
	Value         isValue_ImmediateValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_ImmediateValue) Reset() {
	*x = Value_ImmediateValue{}
	mi := &file_MIL_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_ImmediateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_ImmediateValue) ProtoMessage() {}

func (x *Value_ImmediateValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_ImmediateValue.ProtoReflect.Descriptor instead.
func (*Value_ImmediateValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{13, 0}
}

func (x *Value_ImmediateValue) GetValue() isValue_ImmediateValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value_ImmediateValue) GetTensor() *TensorValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ImmediateValue_Tensor); ok {
			return x.Tensor
		}
	}
	return nil
}

func (x *Value_ImmediateValue) GetTuple() *TupleValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ImmediateValue_Tuple); ok {
			return x.Tuple
		}
	}
	return nil
}

func (x *Value_ImmediateValue) GetList() *ListValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ImmediateValue_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Value_ImmediateValue) GetDictionary() *DictionaryValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ImmediateValue_Dictionary); ok {
			return x.Dictionary
		}
	}
	return nil
}

type isValue_ImmediateValue_Value interface {
	isValue_ImmediateValue_Value()
}

type Value_ImmediateValue_Tensor struct {
	Tensor *TensorValue `protobuf:"bytes,1,opt,name=tensor,proto3,oneof"`
}

type Value_ImmediateValue_Tuple struct {
	Tuple *TupleValue `protobuf:"bytes,2,opt,name=tuple,proto3,oneof"`
}

type Value_ImmediateValue_List struct {
	List *ListValue `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type Value_ImmediateValue_Dictionary struct {
	Dictionary *DictionaryValue `protobuf:"bytes,4,opt,name=dictionary,proto3,oneof"`
}

func (*Value_ImmediateValue_Tensor) isValue_ImmediateValue_Value() {}

func (*Value_ImmediateValue_Tuple) isValue_ImmediateValue_Value() {}

func (*Value_ImmediateValue_List) isValue_ImmediateValue_Value() {}

func (*Value_ImmediateValue_Dictionary) isValue_ImmediateValue_Value() {}

// Reference to a "blob v2" storage file
type Value_BlobFileValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of file
	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	// byte offset to metadata
	Offset        uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_BlobFileValue) Reset() {
	*x = Value_BlobFileValue{}
	mi := &file_MIL_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_BlobFileValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_BlobFileValue) ProtoMessage() {}

func (x *Value_BlobFileValue) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_BlobFileValue.ProtoReflect.Descriptor instead.
func (*Value_BlobFileValue) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{13, 1}
}

func (x *Value_BlobFileValue) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Value_BlobFileValue) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type TensorValue_RepeatedFloats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedFloats) Reset() {
	*x = TensorValue_RepeatedFloats{}
	mi := &file_MIL_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedFloats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedFloats) ProtoMessage() {}

func (x *TensorValue_RepeatedFloats) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedFloats.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedFloats) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 0}
}

func (x *TensorValue_RepeatedFloats) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedDoubles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedDoubles) Reset() {
	*x = TensorValue_RepeatedDoubles{}
	mi := &file_MIL_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedDoubles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedDoubles) ProtoMessage() {}

func (x *TensorValue_RepeatedDoubles) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedDoubles.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedDoubles) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 1}
}

func (x *TensorValue_RepeatedDoubles) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedInts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedInts) Reset() {
	*x = TensorValue_RepeatedInts{}
	mi := &file_MIL_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedInts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedInts) ProtoMessage() {}

func (x *TensorValue_RepeatedInts) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedInts.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedInts) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 2}
}

func (x *TensorValue_RepeatedInts) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedLongInts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedLongInts) Reset() {
	*x = TensorValue_RepeatedLongInts{}
	mi := &file_MIL_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedLongInts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedLongInts) ProtoMessage() {}

func (x *TensorValue_RepeatedLongInts) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedLongInts.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedLongInts) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 3}
}

func (x *TensorValue_RepeatedLongInts) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedBools struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []bool                 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedBools) Reset() {
	*x = TensorValue_RepeatedBools{}
	mi := &file_MIL_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedBools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedBools) ProtoMessage() {}

func (x *TensorValue_RepeatedBools) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedBools.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedBools) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 4}
}

func (x *TensorValue_RepeatedBools) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedStrings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedStrings) Reset() {
	*x = TensorValue_RepeatedStrings{}
	mi := &file_MIL_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedStrings) ProtoMessage() {}

func (x *TensorValue_RepeatedStrings) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedStrings.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedStrings) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 5}
}

func (x *TensorValue_RepeatedStrings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorValue_RepeatedBytes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []byte                 `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorValue_RepeatedBytes) Reset() {
	*x = TensorValue_RepeatedBytes{}
	mi := &file_MIL_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorValue_RepeatedBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorValue_RepeatedBytes) ProtoMessage() {}

func (x *TensorValue_RepeatedBytes) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorValue_RepeatedBytes.ProtoReflect.Descriptor instead.
func (*TensorValue_RepeatedBytes) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{14, 6}
}

func (x *TensorValue_RepeatedBytes) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type DictionaryValue_KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Value                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryValue_KeyValuePair) Reset() {
	*x = DictionaryValue_KeyValuePair{}
	mi := &file_MIL_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryValue_KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryValue_KeyValuePair) ProtoMessage() {}

func (x *DictionaryValue_KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_MIL_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryValue_KeyValuePair.ProtoReflect.Descriptor instead.
func (*DictionaryValue_KeyValuePair) Descriptor() ([]byte, []int) {
	return file_MIL_proto_rawDescGZIP(), []int{17, 0}
}

func (x *DictionaryValue_KeyValuePair) GetKey() *Value {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DictionaryValue_KeyValuePair) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_MIL_proto protoreflect.FileDescriptor

const file_MIL_proto_rawDesc = "" +
	"\n" +
	"\tMIL.proto\x12\x1cCoreML.Specification.MILSpec\"\xb6\x03\n" +
	"\aProgram\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12R\n" +
	"\tfunctions\x18\x02 \x03(\v24.CoreML.Specification.MILSpec.Program.FunctionsEntryR\tfunctions\x12\x1c\n" +
	"\tdocString\x18\x03 \x01(\tR\tdocString\x12U\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v25.CoreML.Specification.MILSpec.Program.AttributesEntryR\n" +
	"attributes\x1ad\n" +
	"\x0eFunctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.CoreML.Specification.MILSpec.FunctionR\x05value:\x028\x01\x1ab\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value:\x028\x01\"\x87\x04\n" +
	"\bFunction\x12D\n" +
	"\x06inputs\x18\x01 \x03(\v2,.CoreML.Specification.MILSpec.NamedValueTypeR\x06inputs\x12\x14\n" +
	"\x05opset\x18\x02 \x01(\tR\x05opset\x12u\n" +
	"\x15block_specializations\x18\x03 \x03(\v2@.CoreML.Specification.MILSpec.Function.BlockSpecializationsEntryR\x14blockSpecializations\x12V\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v26.CoreML.Specification.MILSpec.Function.AttributesEntryR\n" +
	"attributes\x1al\n" +
	"\x19BlockSpecializationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.BlockR\x05value:\x028\x01\x1ab\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value:\x028\x01\"\xe9\x02\n" +
	"\x05Block\x12D\n" +
	"\x06inputs\x18\x01 \x03(\v2,.CoreML.Specification.MILSpec.NamedValueTypeR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x02 \x03(\tR\aoutputs\x12G\n" +
	"\n" +
	"operations\x18\x03 \x03(\v2'.CoreML.Specification.MILSpec.OperationR\n" +
	"operations\x12S\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v23.CoreML.Specification.MILSpec.Block.AttributesEntryR\n" +
	"attributes\x1ab\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value:\x028\x01\"\xc1\x01\n" +
	"\bArgument\x12L\n" +
	"\targuments\x18\x01 \x03(\v2..CoreML.Specification.MILSpec.Argument.BindingR\targuments\x1ag\n" +
	"\aBinding\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12;\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueH\x00R\x05valueB\t\n" +
	"\abinding\"\x91\x04\n" +
	"\tOperation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12K\n" +
	"\x06inputs\x18\x02 \x03(\v23.CoreML.Specification.MILSpec.Operation.InputsEntryR\x06inputs\x12F\n" +
	"\aoutputs\x18\x03 \x03(\v2,.CoreML.Specification.MILSpec.NamedValueTypeR\aoutputs\x12;\n" +
	"\x06blocks\x18\x04 \x03(\v2#.CoreML.Specification.MILSpec.BlockR\x06blocks\x12W\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v27.CoreML.Specification.MILSpec.Operation.AttributesEntryR\n" +
	"attributes\x1aa\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.CoreML.Specification.MILSpec.ArgumentR\x05value:\x028\x01\x1ab\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value:\x028\x01\"a\n" +
	"\x0eNamedValueType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04type\x18\x02 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\x04type\"\x8f\x03\n" +
	"\tValueType\x12J\n" +
	"\n" +
	"tensorType\x18\x01 \x01(\v2(.CoreML.Specification.MILSpec.TensorTypeH\x00R\n" +
	"tensorType\x12D\n" +
	"\blistType\x18\x02 \x01(\v2&.CoreML.Specification.MILSpec.ListTypeH\x00R\blistType\x12G\n" +
	"\ttupleType\x18\x03 \x01(\v2'.CoreML.Specification.MILSpec.TupleTypeH\x00R\ttupleType\x12V\n" +
	"\x0edictionaryType\x18\x04 \x01(\v2,.CoreML.Specification.MILSpec.DictionaryTypeH\x00R\x0edictionaryType\x12G\n" +
	"\tstateType\x18\x05 \x01(\v2'.CoreML.Specification.MILSpec.StateTypeH\x00R\tstateTypeB\x06\n" +
	"\x04type\"\xeb\x02\n" +
	"\n" +
	"TensorType\x12B\n" +
	"\bdataType\x18\x01 \x01(\x0e2&.CoreML.Specification.MILSpec.DataTypeR\bdataType\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x03R\x04rank\x12G\n" +
	"\n" +
	"dimensions\x18\x03 \x03(\v2'.CoreML.Specification.MILSpec.DimensionR\n" +
	"dimensions\x12X\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v28.CoreML.Specification.MILSpec.TensorType.AttributesEntryR\n" +
	"attributes\x1ab\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value:\x028\x01\"J\n" +
	"\tTupleType\x12=\n" +
	"\x05types\x18\x01 \x03(\v2'.CoreML.Specification.MILSpec.ValueTypeR\x05types\"\x88\x01\n" +
	"\bListType\x12;\n" +
	"\x04type\x18\x01 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\x04type\x12?\n" +
	"\x06length\x18\x02 \x01(\v2'.CoreML.Specification.MILSpec.DimensionR\x06length\"\x9a\x01\n" +
	"\x0eDictionaryType\x12A\n" +
	"\akeyType\x18\x01 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\akeyType\x12E\n" +
	"\tvalueType\x18\x02 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\tvalueType\"V\n" +
	"\tStateType\x12I\n" +
	"\vwrappedType\x18\x01 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\vwrappedType\"\xa0\x02\n" +
	"\tDimension\x12W\n" +
	"\bconstant\x18\x01 \x01(\v29.CoreML.Specification.MILSpec.Dimension.ConstantDimensionH\x00R\bconstant\x12T\n" +
	"\aunknown\x18\x02 \x01(\v28.CoreML.Specification.MILSpec.Dimension.UnknownDimensionH\x00R\aunknown\x1a'\n" +
	"\x11ConstantDimension\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x1a.\n" +
	"\x10UnknownDimension\x12\x1a\n" +
	"\bvariadic\x18\x01 \x01(\bR\bvariadicB\v\n" +
	"\tdimension\"\x9c\x05\n" +
	"\x05Value\x12\x1c\n" +
	"\tdocString\x18\x01 \x01(\tR\tdocString\x12;\n" +
	"\x04type\x18\x02 \x01(\v2'.CoreML.Specification.MILSpec.ValueTypeR\x04type\x12\\\n" +
	"\x0eimmediateValue\x18\x03 \x01(\v22.CoreML.Specification.MILSpec.Value.ImmediateValueH\x00R\x0eimmediateValue\x12Y\n" +
	"\rblobFileValue\x18\x05 \x01(\v21.CoreML.Specification.MILSpec.Value.BlobFileValueH\x00R\rblobFileValue\x1a\xb0\x02\n" +
	"\x0eImmediateValue\x12C\n" +
	"\x06tensor\x18\x01 \x01(\v2).CoreML.Specification.MILSpec.TensorValueH\x00R\x06tensor\x12@\n" +
	"\x05tuple\x18\x02 \x01(\v2(.CoreML.Specification.MILSpec.TupleValueH\x00R\x05tuple\x12=\n" +
	"\x04list\x18\x03 \x01(\v2'.CoreML.Specification.MILSpec.ListValueH\x00R\x04list\x12O\n" +
	"\n" +
	"dictionary\x18\x04 \x01(\v2-.CoreML.Specification.MILSpec.DictionaryValueH\x00R\n" +
	"dictionaryB\a\n" +
	"\x05value\x1aC\n" +
	"\rBlobFileValue\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offsetB\a\n" +
	"\x05value\"\x9c\a\n" +
	"\vTensorValue\x12R\n" +
	"\x06floats\x18\x01 \x01(\v28.CoreML.Specification.MILSpec.TensorValue.RepeatedFloatsH\x00R\x06floats\x12L\n" +
	"\x04ints\x18\x02 \x01(\v26.CoreML.Specification.MILSpec.TensorValue.RepeatedIntsH\x00R\x04ints\x12O\n" +
	"\x05bools\x18\x03 \x01(\v27.CoreML.Specification.MILSpec.TensorValue.RepeatedBoolsH\x00R\x05bools\x12U\n" +
	"\astrings\x18\x04 \x01(\v29.CoreML.Specification.MILSpec.TensorValue.RepeatedStringsH\x00R\astrings\x12X\n" +
	"\blongInts\x18\x05 \x01(\v2:.CoreML.Specification.MILSpec.TensorValue.RepeatedLongIntsH\x00R\blongInts\x12U\n" +
	"\adoubles\x18\x06 \x01(\v29.CoreML.Specification.MILSpec.TensorValue.RepeatedDoublesH\x00R\adoubles\x12O\n" +
	"\x05bytes\x18\a \x01(\v27.CoreML.Specification.MILSpec.TensorValue.RepeatedBytesH\x00R\x05bytes\x1a,\n" +
	"\x0eRepeatedFloats\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x02B\x02\x10\x01R\x06values\x1a-\n" +
	"\x0fRepeatedDoubles\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x01B\x02\x10\x01R\x06values\x1a*\n" +
	"\fRepeatedInts\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x05B\x02\x10\x01R\x06values\x1a.\n" +
	"\x10RepeatedLongInts\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x03B\x02\x10\x01R\x06values\x1a+\n" +
	"\rRepeatedBools\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\bB\x02\x10\x01R\x06values\x1a)\n" +
	"\x0fRepeatedStrings\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1a'\n" +
	"\rRepeatedBytes\x12\x16\n" +
	"\x06values\x18\x01 \x01(\fR\x06valuesB\a\n" +
	"\x05value\"I\n" +
	"\n" +
	"TupleValue\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.CoreML.Specification.MILSpec.ValueR\x06values\"H\n" +
	"\tListValue\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.CoreML.Specification.MILSpec.ValueR\x06values\"\xe8\x01\n" +
	"\x0fDictionaryValue\x12R\n" +
	"\x06values\x18\x01 \x03(\v2:.CoreML.Specification.MILSpec.DictionaryValue.KeyValuePairR\x06values\x1a\x80\x01\n" +
	"\fKeyValuePair\x125\n" +
	"\x03key\x18\x01 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.CoreML.Specification.MILSpec.ValueR\x05value*\xa3\x02\n" +
	"\bDataType\x12\x0f\n" +
	"\vUNUSED_TYPE\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\n" +
	"\n" +
	"\x06STRING\x10\x02\x12\x10\n" +
	"\fFLOAT8E4M3FN\x10(\x12\x0e\n" +
	"\n" +
	"FLOAT8E5M2\x10)\x12\v\n" +
	"\aFLOAT16\x10\n" +
	"\x12\v\n" +
	"\aFLOAT32\x10\v\x12\v\n" +
	"\aFLOAT64\x10\f\x12\f\n" +
	"\bBFLOAT16\x10\r\x12\b\n" +
	"\x04INT8\x10\x15\x12\t\n" +
	"\x05INT16\x10\x16\x12\t\n" +
	"\x05INT32\x10\x17\x12\t\n" +
	"\x05INT64\x10\x18\x12\b\n" +
	"\x04INT4\x10\x19\x12\t\n" +
	"\x05UINT8\x10\x1f\x12\n" +
	"\n" +
	"\x06UINT16\x10 \x12\n" +
	"\n" +
	"\x06UINT32\x10!\x12\n" +
	"\n" +
	"\x06UINT64\x10\"\x12\t\n" +
	"\x05UINT4\x10#\x12\t\n" +
	"\x05UINT2\x10$\x12\t\n" +
	"\x05UINT1\x10%\x12\t\n" +
	"\x05UINT6\x10&\x12\t\n" +
	"\x05UINT3\x10'B\x02H\x03b\x06proto3"

var (
	file_MIL_proto_rawDescOnce sync.Once
	file_MIL_proto_rawDescData []byte
)

func file_MIL_proto_rawDescGZIP() []byte {
	file_MIL_proto_rawDescOnce.Do(func() {
		file_MIL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MIL_proto_rawDesc), len(file_MIL_proto_rawDesc)))
	})
	return file_MIL_proto_rawDescData
}

var file_MIL_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MIL_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_MIL_proto_goTypes = []any{
	(DataType)(0),                        // 0: CoreML.Specification.MILSpec.DataType
	(*Program)(nil),                      // 1: CoreML.Specification.MILSpec.Program
	(*Function)(nil),                     // 2: CoreML.Specification.MILSpec.Function
	(*Block)(nil),                        // 3: CoreML.Specification.MILSpec.Block
	(*Argument)(nil),                     // 4: CoreML.Specification.MILSpec.Argument
	(*Operation)(nil),                    // 5: CoreML.Specification.MILSpec.Operation
	(*NamedValueType)(nil),               // 6: CoreML.Specification.MILSpec.NamedValueType
	(*ValueType)(nil),                    // 7: CoreML.Specification.MILSpec.ValueType
	(*TensorType)(nil),                   // 8: CoreML.Specification.MILSpec.TensorType
	(*TupleType)(nil),                    // 9: CoreML.Specification.MILSpec.TupleType
	(*ListType)(nil),                     // 10: CoreML.Specification.MILSpec.ListType
	(*DictionaryType)(nil),               // 11: CoreML.Specification.MILSpec.DictionaryType
	(*StateType)(nil),                    // 12: CoreML.Specification.MILSpec.StateType
	(*Dimension)(nil),                    // 13: CoreML.Specification.MILSpec.Dimension
	(*Value)(nil),                        // 14: CoreML.Specification.MILSpec.Value
	(*TensorValue)(nil),                  // 15: CoreML.Specification.MILSpec.TensorValue
	(*TupleValue)(nil),                   // 16: CoreML.Specification.MILSpec.TupleValue
	(*ListValue)(nil),                    // 17: CoreML.Specification.MILSpec.ListValue
	(*DictionaryValue)(nil),              // 18: CoreML.Specification.MILSpec.DictionaryValue
	nil,                                  // 19: CoreML.Specification.MILSpec.Program.FunctionsEntry
	nil,                                  // 20: CoreML.Specification.MILSpec.Program.AttributesEntry
	nil,                                  // 21: CoreML.Specification.MILSpec.Function.BlockSpecializationsEntry
	nil,                                  // 22: CoreML.Specification.MILSpec.Function.AttributesEntry
	nil,                                  // 23: CoreML.Specification.MILSpec.Block.AttributesEntry
	(*Argument_Binding)(nil),             // 24: CoreML.Specification.MILSpec.Argument.Binding
	nil,                                  // 25: CoreML.Specification.MILSpec.Operation.InputsEntry
	nil,                                  // 26: CoreML.Specification.MILSpec.Operation.AttributesEntry
	nil,                                  // 27: CoreML.Specification.MILSpec.TensorType.AttributesEntry
	(*Dimension_ConstantDimension)(nil),  // 28: CoreML.Specification.MILSpec.Dimension.ConstantDimension
	(*Dimension_UnknownDimension)(nil),   // 29: CoreML.Specification.MILSpec.Dimension.UnknownDimension
	(*Value_ImmediateValue)(nil),         // 30: CoreML.Specification.MILSpec.Value.ImmediateValue
	(*Value_BlobFileValue)(nil),          // 31: CoreML.Specification.MILSpec.Value.BlobFileValue
	(*TensorValue_RepeatedFloats)(nil),   // 32: CoreML.Specification.MILSpec.TensorValue.RepeatedFloats
	(*TensorValue_RepeatedDoubles)(nil),  // 33: CoreML.Specification.MILSpec.TensorValue.RepeatedDoubles
	(*TensorValue_RepeatedInts)(nil),     // 34: CoreML.Specification.MILSpec.TensorValue.RepeatedInts
	(*TensorValue_RepeatedLongInts)(nil), // 35: CoreML.Specification.MILSpec.TensorValue.RepeatedLongInts
	(*TensorValue_RepeatedBools)(nil),    // 36: CoreML.Specification.MILSpec.TensorValue.RepeatedBools
	(*TensorValue_RepeatedStrings)(nil),  // 37: CoreML.Specification.MILSpec.TensorValue.RepeatedStrings
	(*TensorValue_RepeatedBytes)(nil),    // 38: CoreML.Specification.MILSpec.TensorValue.RepeatedBytes
	(*DictionaryValue_KeyValuePair)(nil), // 39: CoreML.Specification.MILSpec.DictionaryValue.KeyValuePair
}
var file_MIL_proto_depIdxs = []int32{
	19, // 0: CoreML.Specification.MILSpec.Program.functions:type_name -> CoreML.Specification.MILSpec.Program.FunctionsEntry
	20, // 1: CoreML.Specification.MILSpec.Program.attributes:type_name -> CoreML.Specification.MILSpec.Program.AttributesEntry
	6,  // 2: CoreML.Specification.MILSpec.Function.inputs:type_name -> CoreML.Specification.MILSpec.NamedValueType
	21, // 3: CoreML.Specification.MILSpec.Function.block_specializations:type_name -> CoreML.Specification.MILSpec.Function.BlockSpecializationsEntry
	22, // 4: CoreML.Specification.MILSpec.Function.attributes:type_name -> CoreML.Specification.MILSpec.Function.AttributesEntry
	6,  // 5: CoreML.Specification.MILSpec.Block.inputs:type_name -> CoreML.Specification.MILSpec.NamedValueType
	5,  // 6: CoreML.Specification.MILSpec.Block.operations:type_name -> CoreML.Specification.MILSpec.Operation
	23, // 7: CoreML.Specification.MILSpec.Block.attributes:type_name -> CoreML.Specification.MILSpec.Block.AttributesEntry
	24, // 8: CoreML.Specification.MILSpec.Argument.arguments:type_name -> CoreML.Specification.MILSpec.Argument.Binding
	25, // 9: CoreML.Specification.MILSpec.Operation.inputs:type_name -> CoreML.Specification.MILSpec.Operation.InputsEntry
	6,  // 10: CoreML.Specification.MILSpec.Operation.outputs:type_name -> CoreML.Specification.MILSpec.NamedValueType
	3,  // 11: CoreML.Specification.MILSpec.Operation.blocks:type_name -> CoreML.Specification.MILSpec.Block
	26, // 12: CoreML.Specification.MILSpec.Operation.attributes:type_name -> CoreML.Specification.MILSpec.Operation.AttributesEntry
	7,  // 13: CoreML.Specification.MILSpec.NamedValueType.type:type_name -> CoreML.Specification.MILSpec.ValueType
	8,  // 14: CoreML.Specification.MILSpec.ValueType.tensorType:type_name -> CoreML.Specification.MILSpec.TensorType
	10, // 15: CoreML.Specification.MILSpec.ValueType.listType:type_name -> CoreML.Specification.MILSpec.ListType
	9,  // 16: CoreML.Specification.MILSpec.ValueType.tupleType:type_name -> CoreML.Specification.MILSpec.TupleType
	11, // 17: CoreML.Specification.MILSpec.ValueType.dictionaryType:type_name -> CoreML.Specification.MILSpec.DictionaryType
	12, // 18: CoreML.Specification.MILSpec.ValueType.stateType:type_name -> CoreML.Specification.MILSpec.StateType
	0,  // 19: CoreML.Specification.MILSpec.TensorType.dataType:type_name -> CoreML.Specification.MILSpec.DataType
	13, // 20: CoreML.Specification.MILSpec.TensorType.dimensions:type_name -> CoreML.Specification.MILSpec.Dimension
	27, // 21: CoreML.Specification.MILSpec.TensorType.attributes:type_name -> CoreML.Specification.MILSpec.TensorType.AttributesEntry
	7,  // 22: CoreML.Specification.MILSpec.TupleType.types:type_name -> CoreML.Specification.MILSpec.ValueType
	7,  // 23: CoreML.Specification.MILSpec.ListType.type:type_name -> CoreML.Specification.MILSpec.ValueType
	13, // 24: CoreML.Specification.MILSpec.ListType.length:type_name -> CoreML.Specification.MILSpec.Dimension
	7,  // 25: CoreML.Specification.MILSpec.DictionaryType.keyType:type_name -> CoreML.Specification.MILSpec.ValueType
	7,  // 26: CoreML.Specification.MILSpec.DictionaryType.valueType:type_name -> CoreML.Specification.MILSpec.ValueType
	7,  // 27: CoreML.Specification.MILSpec.StateType.wrappedType:type_name -> CoreML.Specification.MILSpec.ValueType
	28, // 28: CoreML.Specification.MILSpec.Dimension.constant:type_name -> CoreML.Specification.MILSpec.Dimension.ConstantDimension
	29, // 29: CoreML.Specification.MILSpec.Dimension.unknown:type_name -> CoreML.Specification.MILSpec.Dimension.UnknownDimension
	7,  // 30: CoreML.Specification.MILSpec.Value.type:type_name -> CoreML.Specification.MILSpec.ValueType
	30, // 31: CoreML.Specification.MILSpec.Value.immediateValue:type_name -> CoreML.Specification.MILSpec.Value.ImmediateValue
	31, // 32: CoreML.Specification.MILSpec.Value.blobFileValue:type_name -> CoreML.Specification.MILSpec.Value.BlobFileValue
	32, // 33: CoreML.Specification.MILSpec.TensorValue.floats:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedFloats
	34, // 34: CoreML.Specification.MILSpec.TensorValue.ints:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedInts
	36, // 35: CoreML.Specification.MILSpec.TensorValue.bools:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedBools
	37, // 36: CoreML.Specification.MILSpec.TensorValue.strings:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedStrings
	35, // 37: CoreML.Specification.MILSpec.TensorValue.longInts:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedLongInts
	33, // 38: CoreML.Specification.MILSpec.TensorValue.doubles:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedDoubles
	38, // 39: CoreML.Specification.MILSpec.TensorValue.bytes:type_name -> CoreML.Specification.MILSpec.TensorValue.RepeatedBytes
	14, // 40: CoreML.Specification.MILSpec.TupleValue.values:type_name -> CoreML.Specification.MILSpec.Value
	14, // 41: CoreML.Specification.MILSpec.ListValue.values:type_name -> CoreML.Specification.MILSpec.Value
	39, // 42: CoreML.Specification.MILSpec.DictionaryValue.values:type_name -> CoreML.Specification.MILSpec.DictionaryValue.KeyValuePair
	2,  // 43: CoreML.Specification.MILSpec.Program.FunctionsEntry.value:type_name -> CoreML.Specification.MILSpec.Function
	14, // 44: CoreML.Specification.MILSpec.Program.AttributesEntry.value:type_name -> CoreML.Specification.MILSpec.Value
	3,  // 45: CoreML.Specification.MILSpec.Function.BlockSpecializationsEntry.value:type_name -> CoreML.Specification.MILSpec.Block
	14, // 46: CoreML.Specification.MILSpec.Function.AttributesEntry.value:type_name -> CoreML.Specification.MILSpec.Value
	14, // 47: CoreML.Specification.MILSpec.Block.AttributesEntry.value:type_name -> CoreML.Specification.MILSpec.Value
	14, // 48: CoreML.Specification.MILSpec.Argument.Binding.value:type_name -> CoreML.Specification.MILSpec.Value
	4,  // 49: CoreML.Specification.MILSpec.Operation.InputsEntry.value:type_name -> CoreML.Specification.MILSpec.Argument
	14, // 50: CoreML.Specification.MILSpec.Operation.AttributesEntry.value:type_name -> CoreML.Specification.MILSpec.Value
	14, // 51: CoreML.Specification.MILSpec.TensorType.AttributesEntry.value:type_name -> CoreML.Specification.MILSpec.Value
	15, // 52: CoreML.Specification.MILSpec.Value.ImmediateValue.tensor:type_name -> CoreML.Specification.MILSpec.TensorValue
	16, // 53: CoreML.Specification.MILSpec.Value.ImmediateValue.tuple:type_name -> CoreML.Specification.MILSpec.TupleValue
	17, // 54: CoreML.Specification.MILSpec.Value.ImmediateValue.list:type_name -> CoreML.Specification.MILSpec.ListValue
	18, // 55: CoreML.Specification.MILSpec.Value.ImmediateValue.dictionary:type_name -> CoreML.Specification.MILSpec.DictionaryValue
	14, // 56: CoreML.Specification.MILSpec.DictionaryValue.KeyValuePair.key:type_name -> CoreML.Specification.MILSpec.Value
	14, // 57: CoreML.Specification.MILSpec.DictionaryValue.KeyValuePair.value:type_name -> CoreML.Specification.MILSpec.Value
	58, // [58:58] is the sub-list for method output_type
	58, // [58:58] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_MIL_proto_init() }
func file_MIL_proto_init() {
	if File_MIL_proto != nil {
		return
	}
	file_MIL_proto_msgTypes[6].OneofWrappers = []any{
		(*ValueType_TensorType)(nil),
		(*ValueType_ListType)(nil),
		(*ValueType_TupleType)(nil),
		(*ValueType_DictionaryType)(nil),
		(*ValueType_StateType)(nil),
	}
	file_MIL_proto_msgTypes[12].OneofWrappers = []any{
		(*Dimension_Constant)(nil),
		(*Dimension_Unknown)(nil),
	}
	file_MIL_proto_msgTypes[13].OneofWrappers = []any{
		(*Value_ImmediateValue_)(nil),
		(*Value_BlobFileValue_)(nil),
	}
	file_MIL_proto_msgTypes[14].OneofWrappers = []any{
		(*TensorValue_Floats)(nil),
		(*TensorValue_Ints)(nil),
		(*TensorValue_Bools)(nil),
		(*TensorValue_Strings)(nil),
		(*TensorValue_LongInts)(nil),
		(*TensorValue_Doubles)(nil),
		(*TensorValue_Bytes)(nil),
	}
	file_MIL_proto_msgTypes[23].OneofWrappers = []any{
		(*Argument_Binding_Name)(nil),
		(*Argument_Binding_Value)(nil),
	}
	file_MIL_proto_msgTypes[29].OneofWrappers = []any{
		(*Value_ImmediateValue_Tensor)(nil),
		(*Value_ImmediateValue_Tuple)(nil),
		(*Value_ImmediateValue_List)(nil),
		(*Value_ImmediateValue_Dictionary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MIL_proto_rawDesc), len(file_MIL_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MIL_proto_goTypes,
		DependencyIndexes: file_MIL_proto_depIdxs,
		EnumInfos:         file_MIL_proto_enumTypes,
		MessageInfos:      file_MIL_proto_msgTypes,
	}.Build()
	File_MIL_proto = out.File
	file_MIL_proto_goTypes = nil
	file_MIL_proto_depIdxs = nil
}
